* [32mmain[m
  [31mremotes/origin/07-11-_nested_lines_accommodating_cart_api_changes[m
  [31mremotes/origin/10.0.0-release-branch[m
  [31mremotes/origin/12.0.0[m
  [31mremotes/origin/15.1.0-version-bump[m
  [31mremotes/origin/2p-ads-prototype[m
  [31mremotes/origin/9.0.0-release-branch[m
  [31mremotes/origin/Card-image-border-radius[m
  [31mremotes/origin/Currency-and-language-selector-position[m
  [31mremotes/origin/GalleryEmptySpace[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/MS-WDGLL[m
  [31mremotes/origin/MulticolumnHeadingSize[m
  [31mremotes/origin/Transparent-Backgrounds[m
  [31mremotes/origin/add-animations-on-page[m
  [31mremotes/origin/add-email-signup-redirect-setting[m
  [31mremotes/origin/add-missing-validation[m
  [31mremotes/origin/add-quantity-translations[m
  [31mremotes/origin/add-section-heading-alignment-setting[m
  [31mremotes/origin/add-text-image-sections[m
  [31mremotes/origin/adjacent-conditions-testing[m
  [31mremotes/origin/alpha-color-values[m
  [31mremotes/origin/andrew/quick-order-sticky-headers[m
  [31mremotes/origin/animate-multirow[m
  [31mremotes/origin/animate-on-scroll[m
  [31mremotes/origin/apostrophe-test[m
  [31mremotes/origin/apply-default-styles-andor-presets-to-featured-product-placeholder-image[m
  [31mremotes/origin/b2b/restrict-pricing[m
  [31mremotes/origin/bkbackup[m
  [31mremotes/origin/blocks[m
  [31mremotes/origin/blog-article-ambient[m
  [31mremotes/origin/bulk-quick-add-progress-bar[m
  [31mremotes/origin/buttons-border-refactor[m
  [31mremotes/origin/cart-page-update-fix[m
  [31mremotes/origin/cart-table-roles[m
  [31mremotes/origin/chris/search-metaobject-pages[m
  [31mremotes/origin/collage-ambient-background[m
  [31mremotes/origin/collection-list-at-most[m
  [31mremotes/origin/collection-list-view-all[m
  [31mremotes/origin/color-scheme-default[m
  [31mremotes/origin/combined-listings-reference-theme[m
  [31mremotes/origin/complementary-products[m
  [31mremotes/origin/content-update[m
  [31mremotes/origin/country-width[m
  [31mremotes/origin/custom-logo-width-text[m
  [31mremotes/origin/customer-order-refund-fix-parity-changes[m
  [31mremotes/origin/dawn-global-settings-demo-store[m
  [31mremotes/origin/delivery-options-experiment[m
  [31mremotes/origin/dependabot/github_actions/actions/checkout-5.0.0[m
  [31mremotes/origin/dependabot/github_actions/actions/stale-10[m
  [31mremotes/origin/desktop-header-dropdown-menu-animation-fix[m
  [31mremotes/origin/disable-volume-price-popover[m
  [31mremotes/origin/drawer-filter-accessibility[m
  [31mremotes/origin/drawer-menu-prototype-option-1[m
  [31mremotes/origin/drawer-menu-prototype-option-3[m
  [31mremotes/origin/eugene/quick-order-bulk-fix[m
  [31mremotes/origin/featured-product-richtext[m
  [31mremotes/origin/filter-refactor[m
  [31mremotes/origin/fix-background-gradient-for-related-products[m
  [31mremotes/origin/fix-cart-issue[m
  [31mremotes/origin/fix-checkmark-on-load[m
  [31mremotes/origin/fix-customer-new-address-form-error[m
  [31mremotes/origin/fix-global-js-summary-sibling-selector[m
  [31mremotes/origin/fix-mega-menu-l2-bold-being-overwritten[m
  [31mremotes/origin/fix-mobile-clear-control-role[m
  [31mremotes/origin/fix-product-title-on-search[m
  [31mremotes/origin/fix-quantity-popover-focusout[m
  [31mremotes/origin/fix-quick-add-color-scheme[m
  [31mremotes/origin/fix-related-products-type[m
  [31mremotes/origin/fix-safari-assest-reload-issue[m
  [31mremotes/origin/fix-scroll-when-selecting-variants-on-product-page[m
  [31mremotes/origin/fix-shopify-attributes-announcement-bar[m
  [31mremotes/origin/fix-slider-scrolling-issue[m
  [31mremotes/origin/fix-slider-white-space[m
  [31mremotes/origin/fix-sliders[m
  [31mremotes/origin/fix-social-list-loading[m
  [31mremotes/origin/fix-transparent-img-zoom[m
  [31mremotes/origin/fix-volume-pricing-media-queries[m
  [31mremotes/origin/fix/logo-layout-shift[m
  [31mremotes/origin/fixed-position-image-slideshow[m
  [31mremotes/origin/fixed-position-img-w-text[m
  [31mremotes/origin/fixing-media-jumping[m
  [31mremotes/origin/fixup/prettier-main-collection-banner[m
  [31mremotes/origin/focus-style-refactor[m
  [31mremotes/origin/form-tag[m
  [31mremotes/origin/gb-add-border-to-drawer[m
  [31mremotes/origin/gc-recipient-aria-expanded[m
  [31mremotes/origin/gift-card/add-recipient-isolated[m
  [31mremotes/origin/gift_cards/send_timezone_offset_as_string[m
  [31mremotes/origin/grid-collapse[m
  [31mremotes/origin/grid-corner-collapse[m
  [31mremotes/origin/grid-image-blurry-fix[m
  [31mremotes/origin/hackdays/social-image-previews[m
  [31mremotes/origin/hamideha/selector[m
  [31mremotes/origin/header-app-block[m
  [31mremotes/origin/header-block-test[m
  [31mremotes/origin/header-currency[m
  [31mremotes/origin/header-search-type[m
  [31mremotes/origin/header-sticky-and-logo[m
  [31mremotes/origin/header-transparent[m
  [31mremotes/origin/hide-socials-on-menu-type-drawer-desktop-breakpoint[m
  [31mremotes/origin/horizon-jp-theme[m
  [31mremotes/origin/icon-with-text-copy[m
  [31mremotes/origin/image-banner-settings-adjust[m
  [31mremotes/origin/image-banner-zoom-in[m
  [31mremotes/origin/image-banner-zoom-in-scroll-down-only-zoom[m
  [31mremotes/origin/image-with-text-cascade[m
  [31mremotes/origin/image-with-text-with-borders[m
  [31mremotes/origin/img-ratio-prototype[m
  [31mremotes/origin/img-ratio-prototype-aspect-ratio[m
  [31mremotes/origin/img-ratio-prototype-aspect-ratio-feat-prod[m
  [31mremotes/origin/img-ratio-prototype-aspect-ratio-image-with-text[m
  [31mremotes/origin/img-ratio-prototype-object-fit[m
  [31mremotes/origin/img-ratio-testing-a[m
  [31mremotes/origin/img-ratio-testing-b[m
  [31mremotes/origin/img-ratio-testing-c[m
  [31mremotes/origin/img-ratio-testing-d[m
  [31mremotes/origin/ios-slider-bug[m
  [31mremotes/origin/kai/fix-theme-check-offenses[m
  [31mremotes/origin/kai/make-cart-update-async[m
  [31mremotes/origin/klingbaum/qof-search-prototype[m
  [31mremotes/origin/lang-header[m
  [31mremotes/origin/language-currency-option-1[m
  [31mremotes/origin/language-currency-option-2[m
  [31mremotes/origin/ld-cart-transform-title-override[m
  [31mremotes/origin/lh-prototype-combined-listing-pdp-section-updates[m
  [31mremotes/origin/lh-spike-extract-quantity-form-to-class[m
  [31mremotes/origin/lighthouse-ci[m
  [31mremotes/origin/locale-selector-support-country-flags[m
  [31mremotes/origin/locales-flags[m
  [31mremotes/origin/logical-properties-second-try[m
  [31mremotes/origin/mac-sept10-test[m
  [31mremotes/origin/main[m
  [31mremotes/origin/max-yezhov/gsd-30937-poc[m
  [31mremotes/origin/media-gallery-no-media[m
  [31mremotes/origin/meli-motion-test[m
  [31mremotes/origin/meli-testing[m
  [31mremotes/origin/menu-drawer-localization[m
  [31mremotes/origin/meta-menu-protoype[m
  [31mremotes/origin/mobile_localization_selector_settings_fix[m
  [31mremotes/origin/mt.test-git[m
  [31mremotes/origin/multiple-cart-lines-in-cart-notifications[m
  [31mremotes/origin/old-dawn-testing[m
  [31mremotes/origin/open-modal-a11y[m
  [31mremotes/origin/pdp-color-picker[m
  [31mremotes/origin/performance-preload-test[m
  [31mremotes/origin/ppi-feat-prod[m
  [31mremotes/origin/pr-template-testing-tweak[m
  [31mremotes/origin/pracicot/category_burst[m
  [31mremotes/origin/pracicot/filter_and_visuals[m
  [31mremotes/origin/pracicot/filter_and_viz_Sol1[m
  [31mremotes/origin/pracicot/filter_and_viz_Sol2[m
  [31mremotes/origin/pracicot/filter_and_viz_Sol3[m
  [31mremotes/origin/pracicot/filter_and_viz_Sol4[m
  [31mremotes/origin/pracicot/filter_and_viz_Sol5[m
  [31mremotes/origin/pracicot/filter_and_viz_Sol7[m
  [31mremotes/origin/pracicot/filter_and_viz_Sol8[m
  [31mremotes/origin/pracicot/filter_and_viz_base[m
  [31mremotes/origin/pracicot/filter_and_viz_checkbox[m
  [31mremotes/origin/product-description-section[m
  [31mremotes/origin/product-disabled-input-update[m
  [31mremotes/origin/product-information-color-picker[m
  [31mremotes/origin/product-information-copy-name[m
  [31mremotes/origin/product-media-layout-temp[m
  [31mremotes/origin/product-page-design-tests[m
  [31mremotes/origin/product-page-img-ratio[m
  [31mremotes/origin/product-recos-slider[m
  [31mremotes/origin/product-review-seo[m
  [31mremotes/origin/proto/all-in-menu-style-images[m
  [31mremotes/origin/proto/block-styles-header[m
  [31mremotes/origin/proto/main-menu-block[m
  [31mremotes/origin/proto/mega-menu[m
  [31mremotes/origin/proto/menu-block-with-promo-and-images[m
  [31mremotes/origin/proto/menu-nav-images[m
  [31mremotes/origin/prototype-animation-announcement-bar[m
  [31mremotes/origin/prototype-color-options[m
  [31mremotes/origin/prototype-lazy-loading-setting[m
  [31mremotes/origin/prototype-quantity-rules-metafields[m
  [31mremotes/origin/pull-in-fixes-from-release-10.0.0[m
  [31mremotes/origin/qtyrules-updatecart[m
  [31mremotes/origin/quick-add-bulk-errors[m
  [31mremotes/origin/quick-add-bulk-grid-popover[m
  [31mremotes/origin/quick-add-bulk-original[m
  [31mremotes/origin/quick-add-bulk-related-prods[m
  [31mremotes/origin/quick-order-add[m
  [31mremotes/origin/quick-order-bulk-add-new[m
  [31mremotes/origin/quick-order-form[m
  [31mremotes/origin/quick-order-sticky-header[m
  [31mremotes/origin/quick_order_form_multi_products[m
  [31mremotes/origin/quickorderform[m
  [31mremotes/origin/quickorderform-test[m
  [31mremotes/origin/release/10.0.0[m
  [31mremotes/origin/release/11.0.0-rc[m
  [31mremotes/origin/release/13.0.0[m
  [31mremotes/origin/release/13.0.1[m
  [31mremotes/origin/release/14.0.0[m
  [31mremotes/origin/release/15.0.0[m
  [31mremotes/origin/release/15.0.1[m
  [31mremotes/origin/release/15.1.0[m
  [31mremotes/origin/release/15.1.1[m
  [31mremotes/origin/release/15.2.0[m
  [31mremotes/origin/release/15.4.0[m
  [31mremotes/origin/remove-empty-space-from-inventory-status[m
  [31mremotes/origin/remove-styling-from-svg-files[m
  [31mremotes/origin/remove-try-from-decimal-list[m
  [31mremotes/origin/rename-additional-from-variant-list-to-quick-order-list[m
  [31mremotes/origin/revert-2464-shadow-fix-local-selector-drawer[m
  [31mremotes/origin/revert-3228-fix-product-title-on-search[m
  [31mremotes/origin/richtext-to-inline-richtext[m
  [31mremotes/origin/search-result-ios-fix[m
  [31mremotes/origin/section-border-collapse[m
  [31mremotes/origin/section-image-size-prototype[m
  [31mremotes/origin/shadow-fix-local-selector-drawer[m
  [31mremotes/origin/shopify-add-oxygen-workflow-6dmb[m
  [31mremotes/origin/shopify-add-oxygen-workflow-6exf[m
  [31mremotes/origin/shopify-add-oxygen-workflow-6hhs[m
  [31mremotes/origin/shopify-add-oxygen-workflow-qyn8[m
  [31mremotes/origin/shopify-add-oxygen-workflow-u3mt[m
  [31mremotes/origin/shopify-add-oxygen-workflow-yd15[m
  [31mremotes/origin/shopify-build-add-dawn[m
  [31mremotes/origin/shopify-setup-oxygen-workflow-cq36[m
  [31mremotes/origin/smaller-swatches-on-mobile[m
  [31mremotes/origin/split-slider-components[m
  [31mremotes/origin/storefront-search-fix-search-result-unavailable-error-display[m
  [31mremotes/origin/stu/animate-fade-in-fix[m
  [31mremotes/origin/stu/animate-featured-collection[m
  [31mremotes/origin/stu/animate-featured-collection-2[m
  [31mremotes/origin/stu/animation-approach[m
  [31mremotes/origin/stu/high-density-images[m
  [31mremotes/origin/stu/log-lighthouse-to-observe[m
  [31mremotes/origin/stu/remove-lazy-loading[m
  [31mremotes/origin/stu/scroll-trigger[m
  [31mremotes/origin/stu/test-setting-change[m
  [31mremotes/origin/subcolletion-demo[m
  [31mremotes/origin/svg-component[m
  [31mremotes/origin/svg-img-tags[m
  [31mremotes/origin/swatch-border-contrast[m
  [31mremotes/origin/temp[m
  [31mremotes/origin/temp-announcement-bar-animation-issue[m
  [31mremotes/origin/temp-fix-announcement-bar-animation-scroll-snap[m
  [31mremotes/origin/temp-kjell-motion-demo-april-5-2023[m
  [31mremotes/origin/test-lighthouse[m
  [31mremotes/origin/test-product-description-collapsible[m
  [31mremotes/origin/test-product-description-section-level-collapsible[m
  [31mremotes/origin/test-product-description-setting-in-sections[m
  [31mremotes/origin/test-variant-picker-soldout[m
  [31mremotes/origin/test/theme-check-2.0-ci[m
  [31mremotes/origin/testing[m
  [31mremotes/origin/text-opacity-a11y[m
  [31mremotes/origin/theme-design-ci[m
  [31mremotes/origin/throttle-issue[m
  [31mremotes/origin/thumbnail-vertical-test[m
  [31mremotes/origin/tophat-branch[m
  [31mremotes/origin/translation-platform/pr/2627[m
  [31mremotes/origin/translation-platform/pr/2825[m
  [31mremotes/origin/try-image-filters[m
  [31mremotes/origin/try/8-columns[m
  [31mremotes/origin/try/announcement-bar-padding[m
  [31mremotes/origin/try/announcement-font-size[m
  [31mremotes/origin/try/collection-banner-padding[m
  [31mremotes/origin/try/footer-separator-line-option[m
  [31mremotes/origin/try/heading-preset-for-rich-text[m
  [31mremotes/origin/try/image-preset-for-image-banner[m
  [31mremotes/origin/try/image-shapes-image-with-text[m
  [31mremotes/origin/try/motion-explorations[m
  [31mremotes/origin/try/other-utility-bar-fixes[m
  [31mremotes/origin/try/responsive-type-sizes[m
  [31mremotes/origin/try/scoll-animations[m
  [31mremotes/origin/try/shiny-card-effect-on-hover[m
  [31mremotes/origin/try/text-collection-section[m
  [31mremotes/origin/update-french-translation[m
  [31mremotes/origin/update-label[m
  [31mremotes/origin/update-portrait-ratio[m
  [31mremotes/origin/updated-unit-price-support[m
  [31mremotes/origin/updates-to-option-value-picker[m
  [31mremotes/origin/upgrade-lighthouse[m
  [31mremotes/origin/use-preload-tag-demo[m
  [31mremotes/origin/utility-bar-blocks[m
  [31mremotes/origin/utility-bar-localization-blk[m
  [31mremotes/origin/utility-bar-prototype[m
  [31mremotes/origin/variant-grid[m
  [31mremotes/origin/variant-grid-new[m
  [31mremotes/origin/variant-picker-sold-out-ui-temporary-js[m
  [31mremotes/origin/vertical-thumbnails[m
  [31mremotes/origin/video-section-ambient[m
  [31mremotes/origin/wip/prettier[m
  [31mremotes/origin/wip/prettier-2[m
